#define TOKEN_EOL                              1
#define TOKEN_MESSAGE                          2
#define TOKEN_ADDR_DIRECTIVE                   3
#define TOKEN_IMMEDIATE                        4
#define TOKEN_IDENTIFIER                       5
#define TOKEN_LABEL_DIRECTIVE                  6
#define TOKEN_CHARACTER                        7
#define TOKEN_VAR_DIRECTIVE                    8
#define TOKEN_CONST_DIRECTIVE                  9
#define TOKEN_NOP                             10
#define TOKEN_MOV                             11
#define TOKEN_REGISTER                        12
#define TOKEN_ADD                             13
#define TOKEN_SWR                             14
#define TOKEN_AWR                             15
#define TOKEN_SUB                             16
#define TOKEN_MUL                             17
#define TOKEN_DIV                             18
#define TOKEN_CMP                             19
#define TOKEN_JMP                             20
#define TOKEN_JEQ                             21
#define TOKEN_JNE                             22
#define TOKEN_JGR                             23
#define TOKEN_JLS                             24
#define TOKEN_CALL                            25
#define TOKEN_RET                             26
#define TOKEN_AND                             27
#define TOKEN_OR                              28
#define TOKEN_XOR                             29
#define TOKEN_NOT                             30
#define TOKEN_NEG                             31
#define TOKEN_LOAD                            32
#define TOKEN_LOADP                           33
#define TOKEN_STOR                            34
#define TOKEN_STORP                           35
#define TOKEN_PUSH                            36
#define TOKEN_POP                             37
#define TOKEN_AUX                             38
